//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AwardsSharePlayer
    {
        public string awardID { get; set; }
        public short yearID { get; set; }
        public string lgID { get; set; }
        public string playerID { get; set; }
        public Nullable<double> pointsWon { get; set; }
        public Nullable<short> pointsMax { get; set; }
        public Nullable<double> votesFirst { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
