//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattingPost
    {
        public short yearID { get; set; }
        public string round { get; set; }
        public string playerID { get; set; }
        public string teamID { get; set; }
        public string lgID { get; set; }
        public Nullable<short> G { get; set; }
        public Nullable<short> AB { get; set; }
        public Nullable<short> R { get; set; }
        public Nullable<short> H { get; set; }
        public Nullable<short> C2B { get; set; }
        public Nullable<short> C3B { get; set; }
        public Nullable<short> HR { get; set; }
        public Nullable<short> RBI { get; set; }
        public Nullable<short> SB { get; set; }
        public Nullable<short> CS { get; set; }
        public Nullable<short> BB { get; set; }
        public Nullable<short> SO { get; set; }
        public Nullable<short> IBB { get; set; }
        public Nullable<short> HBP { get; set; }
        public Nullable<short> SH { get; set; }
        public Nullable<short> SF { get; set; }
        public Nullable<short> GIDP { get; set; }
    }
}
