//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagersHalf
    {
        public string playerID { get; set; }
        public short yearID { get; set; }
        public string teamID { get; set; }
        public string lgID { get; set; }
        public Nullable<short> inseason { get; set; }
        public short half { get; set; }
        public Nullable<short> G { get; set; }
        public Nullable<short> W { get; set; }
        public Nullable<short> L { get; set; }
        public Nullable<short> rank { get; set; }
    }
}
