//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LahmanEntities : DbContext
    {
        public LahmanEntities()
            : base("name=LahmanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllstarFull> AllstarFulls { get; set; }
        public virtual DbSet<Appearance> Appearances { get; set; }
        public virtual DbSet<AwardsManager> AwardsManagers { get; set; }
        public virtual DbSet<AwardsPlayer> AwardsPlayers { get; set; }
        public virtual DbSet<AwardsShareManager> AwardsShareManagers { get; set; }
        public virtual DbSet<AwardsSharePlayer> AwardsSharePlayers { get; set; }
        public virtual DbSet<Batting> Battings { get; set; }
        public virtual DbSet<BattingPost> BattingPosts { get; set; }
        public virtual DbSet<Fielding> Fieldings { get; set; }
        public virtual DbSet<FieldingOF> FieldingOFs { get; set; }
        public virtual DbSet<FieldingOFsplit> FieldingOFsplits { get; set; }
        public virtual DbSet<FieldingPost> FieldingPosts { get; set; }
        public virtual DbSet<HallOfFame> HallOfFames { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<ManagersHalf> ManagersHalves { get; set; }
        public virtual DbSet<Master> Masters { get; set; }
        public virtual DbSet<Park> Parks { get; set; }
        public virtual DbSet<Pitching> Pitchings { get; set; }
        public virtual DbSet<PitchingPost> PitchingPosts { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<SeriesPost> SeriesPosts { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TeamsFranchis> TeamsFranchises { get; set; }
        public virtual DbSet<TeamsHalf> TeamsHalves { get; set; }
        public virtual DbSet<CollegePlaying> CollegePlayings { get; set; }
    }
}
