//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pitching
    {
        public string playerID { get; set; }
        public short yearID { get; set; }
        public short stint { get; set; }
        public string teamID { get; set; }
        public string lgID { get; set; }
        public Nullable<short> W { get; set; }
        public Nullable<short> L { get; set; }
        public Nullable<short> G { get; set; }
        public Nullable<short> GS { get; set; }
        public Nullable<short> CG { get; set; }
        public Nullable<short> SHO { get; set; }
        public Nullable<short> SV { get; set; }
        public Nullable<int> IPouts { get; set; }
        public Nullable<short> H { get; set; }
        public Nullable<short> ER { get; set; }
        public Nullable<short> HR { get; set; }
        public Nullable<short> BB { get; set; }
        public Nullable<short> SO { get; set; }
        public Nullable<double> BAOpp { get; set; }
        public Nullable<double> ERA { get; set; }
        public Nullable<short> IBB { get; set; }
        public Nullable<short> WP { get; set; }
        public Nullable<short> HBP { get; set; }
        public Nullable<short> BK { get; set; }
        public Nullable<short> BFP { get; set; }
        public Nullable<short> GF { get; set; }
        public Nullable<short> R { get; set; }
        public Nullable<short> SH { get; set; }
        public Nullable<short> SF { get; set; }
        public Nullable<short> GIDP { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
