//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LahmanDatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllstarFull
    {
        public string playerID { get; set; }
        public short yearID { get; set; }
        public short gameNum { get; set; }
        public string gameID { get; set; }
        public string teamID { get; set; }
        public string lgID { get; set; }
        public Nullable<short> GP { get; set; }
        public Nullable<short> startingPos { get; set; }
    }
}
