//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LahmanDatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master
    {
        public string playerID { get; set; }
        public Nullable<short> birthYear { get; set; }
        public Nullable<short> birthMonth { get; set; }
        public Nullable<short> birthDay { get; set; }
        public string birthCountry { get; set; }
        public string birthState { get; set; }
        public string birthCity { get; set; }
        public Nullable<short> deathYear { get; set; }
        public Nullable<short> deathMonth { get; set; }
        public Nullable<short> deathDay { get; set; }
        public string deathCountry { get; set; }
        public string deathState { get; set; }
        public string deathCity { get; set; }
        public string nameFirst { get; set; }
        public string nameLast { get; set; }
        public string nameGiven { get; set; }
        public Nullable<short> weight { get; set; }
        public Nullable<short> height { get; set; }
        public string bats { get; set; }
        public string throws { get; set; }
        public string debut { get; set; }
        public string finalGame { get; set; }
        public string retroID { get; set; }
        public string bbrefID { get; set; }
    }
}
