//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LahmanDatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamsFranchis
    {
        public string franchID { get; set; }
        public string franchName { get; set; }
        public string active { get; set; }
        public string NAassoc { get; set; }
    }
}
