//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LahmanDatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamsHalf
    {
        public short yearID { get; set; }
        public string lgID { get; set; }
        public string teamID { get; set; }
        public string Half { get; set; }
        public string divID { get; set; }
        public string DivWin { get; set; }
        public Nullable<short> Rank { get; set; }
        public Nullable<short> G { get; set; }
        public Nullable<short> W { get; set; }
        public Nullable<short> L { get; set; }
    }
}
