//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LahmanDatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public short yearID { get; set; }
        public string lgID { get; set; }
        public string teamID { get; set; }
        public string franchID { get; set; }
        public string divID { get; set; }
        public Nullable<short> Rank { get; set; }
        public Nullable<short> G { get; set; }
        public Nullable<short> Ghome { get; set; }
        public Nullable<short> W { get; set; }
        public Nullable<short> L { get; set; }
        public string DivWin { get; set; }
        public string WCWin { get; set; }
        public string LgWin { get; set; }
        public string WSWin { get; set; }
        public Nullable<short> R { get; set; }
        public Nullable<short> AB { get; set; }
        public Nullable<short> H { get; set; }
        public Nullable<short> C2B { get; set; }
        public Nullable<short> C3B { get; set; }
        public Nullable<short> HR { get; set; }
        public Nullable<short> BB { get; set; }
        public Nullable<short> SO { get; set; }
        public Nullable<short> SB { get; set; }
        public Nullable<short> CS { get; set; }
        public Nullable<short> HBP { get; set; }
        public Nullable<short> SF { get; set; }
        public Nullable<short> RA { get; set; }
        public Nullable<short> ER { get; set; }
        public Nullable<double> ERA { get; set; }
        public Nullable<short> CG { get; set; }
        public Nullable<short> SHO { get; set; }
        public Nullable<short> SV { get; set; }
        public Nullable<int> IPouts { get; set; }
        public Nullable<short> HA { get; set; }
        public Nullable<short> HRA { get; set; }
        public Nullable<short> BBA { get; set; }
        public Nullable<short> SOA { get; set; }
        public Nullable<int> E { get; set; }
        public Nullable<int> DP { get; set; }
        public Nullable<double> FP { get; set; }
        public string name { get; set; }
        public string park { get; set; }
        public Nullable<int> attendance { get; set; }
        public Nullable<int> BPF { get; set; }
        public Nullable<int> PPF { get; set; }
        public string teamIDBR { get; set; }
        public string teamIDlahman45 { get; set; }
        public string teamIDretro { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
