//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldingPost
    {
        public string playerID { get; set; }
        public short yearID { get; set; }
        public string teamID { get; set; }
        public string lgID { get; set; }
        public string round { get; set; }
        public string POS { get; set; }
        public Nullable<short> G { get; set; }
        public Nullable<short> GS { get; set; }
        public Nullable<short> InnOuts { get; set; }
        public Nullable<short> PO { get; set; }
        public Nullable<short> A { get; set; }
        public Nullable<short> E { get; set; }
        public Nullable<short> DP { get; set; }
        public Nullable<short> TP { get; set; }
        public Nullable<short> PB { get; set; }
        public Nullable<short> SB { get; set; }
        public Nullable<short> CS { get; set; }
    }
}
