//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldingOF
    {
        public string playerID { get; set; }
        public short yearID { get; set; }
        public short stint { get; set; }
        public Nullable<short> Glf { get; set; }
        public Nullable<short> Gcf { get; set; }
        public Nullable<short> Grf { get; set; }
    }
}
