//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HallOfFame
    {
        public string playerID { get; set; }
        public short yearid { get; set; }
        public string votedBy { get; set; }
        public Nullable<short> ballots { get; set; }
        public Nullable<short> needed { get; set; }
        public Nullable<short> votes { get; set; }
        public string inducted { get; set; }
        public string category { get; set; }
        public string needed_note { get; set; }
    }
}
